/*醫院配置*/
CREATE TABLE HOSPITAL(
	ID int NOT NULL AUTO_INCREMENT,
	HOSPITAL_NAME VARCHAR(100) DEFAULT NULL, /*醫院名稱*/
	HOSPITAL_CODE VARCHAR(30) DEFAULT NULL, /*醫院代號*/
	API_URL VARCHAR(100) DEFAULT NULL, /*API網址*/
	SIGN_KEY  VARCHAR(50) DEFAULT NULL, /*簽章密鑰*/
	CONTACTS_NAME VARCHAR(50) DEFAULT NULL, /*聯絡人*/
	CONTACTS_PHONE VARCHAR(50) DEFAULT NULL, /*聯絡人電話*/
	STATUS VARCHAR(10) NOT NULL DEFAULT '0', /*醫院狀態*/
	CREATE_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, /*建立時間*/
	UPDATE_TIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP /*更新時間*/
);